[package]
name = "codingame-spring-challenge-2021"
version = "0.1.0"
authors = ["Gabriel Restori Soares <grsoares21@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]